#!/usr/bin/env bash

if ! [ -x "$(command -v brew)" ]; then
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
fi

brew install bit-git
brew install chezmoi
brew install antibody
brew install fzf

brew tap homebrew/cask-fonts
brew install font-caskaydia-cove-nerd-font

osascript -e 'tell application "System Preferences" to quit'

defaults write 'Apple Global Domain' AppleInterfaceStyle -string Dark
